export const EGFP =
  "MVSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITLGMDELYK";

export const FIVE_PRIME_HUMAN_ALPHA_GLOBIN =
  "ACTCTTCTGGTCCCCACAGACTCAGAGAGAACCCACC";
export const THREE_PRIME_HUMAN_ALPHA_GLOBIN =
  "GCTGGAGCCTCGGTGGCCATGCTTCTTGCCCCTTGGGCCTCCCCCCAGCCCCTCCTCCCCTTCCTGCACCCGTACCCCCGTGGTCTTTGAATAAAGTCTGAGTGGGCGGCA";

export const ORGANISMS = [
  { label: "Human", value: "kazusa-9606" },
  { label: "Mouse", value: "kazusa-10090" },
];
