import * as fs from "node:fs";
import { Button, Group, Stack, Text, Title } from "@mantine/core";
import { Link, createFileRoute, useRouter } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";

export const Route = createFileRoute("/")({
  component: Home,
});

function Home() {
  return (
    <Stack>
      <Title>Welcome to mRNArchitect!</Title>
      <Text>
        mRNArchitect is a software toolkit to assist in the design of mRNA
        sequences. mRNArchitect can rapidly assemble and optimize mRNA sequences
        based on user requirements, including GC content, secondary structure,
        codon optimization, and uridine depletion. The sequences generated by
        mRNArchitect can also be readily synthesized, and have been
        experimentally validated across a variety of applications.
      </Text>
      <Group justify="end">
        <Link to="/optimizer">
          {({ isActive }) => <Button size="lg">Get started!</Button>}
        </Link>
      </Group>
    </Stack>
  );
}
