export const EGFP =
  "MVSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITLGMDELYK";

export const FIVE_PRIME_HUMAN_ALPHA_GLOBIN =
  "ACTCTTCTGGTCCCCACAGACTCAGAGAGAACCCACC";
export const THREE_PRIME_HUMAN_ALPHA_GLOBIN =
  "GCTGGAGCCTCGGTGGCCATGCTTCTTGCCCCTTGGGCCTCCCCCCAGCCCCTCCTCCCCTTCCTGCACCCGTACCCCCGTGGTCTTTGAATAAAGTCTGAGTGGGCGGCA";

export const ORGANISMS = [
  { label: "Human", value: "human" },
  { label: "Mouse", value: "mouse" },
];

export const FIVE_PRIME_UTRS = [
  {
    label: "Human alpha-globin",
    value: "ACTCTTCTGGTCCCCACAGACTCAGAGAGAACCCACC",
  },
  {
    label: "Human beta-globin",
    value: "TACATTTGCTTCTGACACAACTGTGTTCACTAGCAACCTCAAACAGACACC",
  },
  {
    label: "Beta actin",
    value: "CCCGCGAGCACAGAGCCTCGCCTTTGCCGATCCGCCGCCCGTCCACACCCGCCGCCAGCTCACC",
  },
  {
    label: "Albumin",
    value: "CTAGCTTTTCTCTTCTGTCAACCCCACACGCCTTTGGCACA",
  },
  {
    label: "Minimal",
    value: "GAGACT",
  },
];
