/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OptimizerImport } from './routes/optimizer'
import { Route as AnotherToolImport } from './routes/another-tool'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const OptimizerRoute = OptimizerImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRoute,
} as any)

const AnotherToolRoute = AnotherToolImport.update({
  id: '/another-tool',
  path: '/another-tool',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/another-tool': {
      id: '/another-tool'
      path: '/another-tool'
      fullPath: '/another-tool'
      preLoaderRoute: typeof AnotherToolImport
      parentRoute: typeof rootRoute
    }
    '/optimizer': {
      id: '/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof OptimizerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/another-tool': typeof AnotherToolRoute
  '/optimizer': typeof OptimizerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/another-tool': typeof AnotherToolRoute
  '/optimizer': typeof OptimizerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/another-tool': typeof AnotherToolRoute
  '/optimizer': typeof OptimizerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/another-tool' | '/optimizer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/another-tool' | '/optimizer'
  id: '__root__' | '/' | '/another-tool' | '/optimizer'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotherToolRoute: typeof AnotherToolRoute
  OptimizerRoute: typeof OptimizerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotherToolRoute: AnotherToolRoute,
  OptimizerRoute: OptimizerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/another-tool",
        "/optimizer"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/another-tool": {
      "filePath": "another-tool.tsx"
    },
    "/optimizer": {
      "filePath": "optimizer.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
