name: deploy
on:
  workflow_call:
    inputs:
      tag:
        description: The image tag.
        type: string
        required: true
    outputs:
      image-uri:
        description: The URI of the newly pushed image.
        value: ${{ jobs.build-and-push.outputs.image-uri }}


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.build-and-push-outputs.outputs.image-uri }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::340752831962:role/deploy
      - uses: aws-actions/amazon-ecr-login@v2
        id: ecr
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.ecr.outputs.registry }}/app:${{ inputs.tag }}
          provenance: false
          cache-from: type=registry,ref=${{ steps.ecr.outputs.registry }}/app:buildcache
          cache-to: type=registry,ref=${{ steps.ecr.outputs.registry }}/app:buildcache,mode=max
      - id: build-and-push-outputs
        run: |
         echo "image-uri=${{ steps.ecr.outputs.registry }}/app:${{ inputs.tag }}" >> "$GITHUB_OUTPUT"

