name: deploy
on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  LAMBDA_FUNCTION_NAME: app

jobs:
  build-push-and-deploy:
    uses: ./.github/workflows/build-push-and-deploy.yml
    with:
      image-tag: production-${{ github.sha }}
      lambda-function-alias: pr-${{ github.event.pull_request.number }}

  e2e-test:
    needs: [build-push-and-deploy]
    uses: ./.github/workflows/e2e.yml
    with:
      playwright-base-url: ${{ needs.build-push-and-deploy.outputs.lambda-function-url }}

  deploy-production:
    needs: [build-and-deploy, e2e-test]
    runs-on: ubuntu-latest
    env:
      LAMBDA_VERSION: ${{ needs.build-and-deploy.outputs.lambda-version }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::340752831962:role/deploy
      - name: Publish lambda version for PRODUCTION
        run: |
          aws lambda update-alias \
            --function-name app \
            --name PRODUCTION \
            --function-version $LAMBDA_VERSION

  e2e-production:
    needs: [deploy-production]
    uses: ./.github/workflows/e2e.yml
    with:
      playwright-base-url: https://app.basefacility.org.au

