name: e2e
on:
  pull_request:

jobs:
  test:
    name: e2e
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          # avoids having to export the local image
          # see: https://docs.docker.com/build/builders/drivers/
          driver: docker
      - uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TAG }}
          target: e2e
          #cache-from: type=gha
          #cache-to: type=gha,mode=max
      - run: docker run --rm --env CI=true $TAG pnpm playwright test
