name: pr
on:
  pull_request:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  test:
    uses: ./.github/workflows/test.yml
  e2e:
    uses: ./.github/workflows/e2e.yml
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      tag: pr-${{ github.sha }}
  deploy-pr-version:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::340752831962:role/deploy
      - name: deploy lambda
        id: deploy-lambda
        env:
          IMAGE_URI: ${{ needs.build-and-push.outputs.image-uri }}
          FUNCTION_ALIAS: ${{ github.sha }}
        shell: bash
        run: |
          FUNCTION_URL=$( \
            uv run .github/scripts/deploy-lambda-version.py \
              --image-uri "$IMAGE_URI" \
              --function-alias "$FUNCTION_ALIAS" \
          )
          echo "function-url=$FUNCTION_URL" >> "$GITHUB_OUTPUT"
  prune-lambda-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: |
          uv run .github/scripts/prune-lambda-versions.py


