name: pr
on:
  pull_request:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required to interact with pull requests

jobs:
  test:
    uses: ./.github/workflows/test.yml

  e2e:
    uses: ./.github/workflows/e2e.yml

  build-push-and-deploy:
    uses: ./.github/workflows/build-push-and-deploy.yml
    with:
      image-tag: pr-${{ github.sha }}
      lambda-function-alias: pr-${{ github.event.pull_request.number }}

  e2e-lambda:
    needs: [build-push-and-deploy]
    uses: ./.github/workflows/e2e.yml
    with:
      playwright-base-url: ${{ needs.build-push-and-deploy.outputs.lambda-function-url }}

  comment-function-url:
    needs: [build-push-and-deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --edit-last --create-if-none --body "AWS Lambda URL: ${{ needs.build-push-and-deploy.outputs.lambda-function-url }}"

  prune-lambda-versions:
    needs: [build-push-and-deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::340752831962:role/deploy
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run .github/scripts/prune-lambda-versions.py ${{ github.repository }}
