name: Test
on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TAG }}
      - run: docker run --rm $TAG echo "No tests!!!"
