name: test
on:
  workflow_call:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::340752831962:role/deploy
      - uses: aws-actions/amazon-ecr-login@v2
        id: ecr
      - uses: docker/setup-buildx-action@v3
        with:
          # avoids having to export the local image
          # see: https://docs.docker.com/build/builders/drivers/
          driver: docker
      - uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TAG }}
          target: dev
          cache-from: type=registry,ref=${{ steps.ecr.outputs.registry }}/app:buildcache
      - run: docker run --rm $TAG pnpm check
      - run: docker run --rm $TAG pnpm vitest run --dir frontend
      - run: docker run --rm $TAG uv run ruff check --diff
      - run: docker run --rm $TAG uv run ty check
      - run: docker run --rm $TAG uv run pytest
      - run: docker run --rm $TAG uv run mRNArchitect optimize ACGACG
