name: Test
on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TAG }}
          target: dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: docker run --rm $TAG pnpm biome check
      - run: docker run --rm $TAG pnpm tsc --noEmit
      - run: docker run --rm $TAG uv run ruff check --diff
      - run: docker run --rm $TAG uv run pyright
      - run: docker run --rm $TAG pytest
