name: test
on:
  workflow_call:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --locked
      - run: uv run ruff check --diff
      - run: uv run pyright
      - run: uv run pytest
